module.exports = {
    ERROR_CODES: {
        "ER_001": "invalid price of ticket entry",
        "ER_002": "invalid participants",
        "ER_003": "Game is not complete",
        "ER_004": "Invalid amount received",
        "ER_005": "Game has ended!",
        "ER_006": "Already Entered",
        "ER_007": "Required endorsers not met, game not started",
        "ER_008": "Cannot refund if game is not cancelled",
        "ER_009": "Cannot refund account, not a participant or refund claimed",
        "ER_010": "Cannot refund endorsement, game is not cancelled",
        "ER_011": "Not an endorser or already claimed refund",
        "ER_012": "Cannot withdraw if the game is not completed",
        "ER_013": "Cannot claim the prize!",
        "ER_014": "Winners prize already claimed",
        "ER_015": "Cannot claim endorsement fee if the game is not completed",
        "ER_016": "There are no required endorsers for this game",
        "ER_017": "Cannot claim endorsement fee because sender is not an endorser",
        "ER_018": "Cannot withdraw from DAO, game has been cancelled",
        "ER_019": "Cannot withdraw from DAO, not beneficiary",
        "ER_020": "Cannot withdraw dao fund, game is not completed",
        "ER_021": "Cannot withdraw from DAO fund, DAO fund already claimed",
        "ER_022": "Game is completed, cannot cancel",
        "ER_023": "cannot receive funds externally (receive)",
        "ER_024": "cannot receive funds externally (fallback)",
        "ER_025": "Can only receive tokens from the social token contract",
        "ER_026": "Can only endorse once",
        "ER_027": "Sufficient endorsements received to begin game",
        "ER_028": "Game start can only be called by owner",
        "ER_029": "Game not valid",
        "ER_030": "Cannot register player as the game id is not owned",
        "ER_031": "Not an active game",
        "ER_032": "Game is not active",
        "ER_033": "Invalid Token Id",
        "ER_034": "Cannot transfer tokens when game is still active",
        "ER_035": "slicing out of range",
    }
};